### ISSUE TITLE
Plugin should validate correct SSL/TLS configuration if ssl_enable is true.

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-input-tcp#42]
```
% bin/logstash -e 'input { tcp { ssl_enable => true port => 12345 } }'
Settings: Default pipeline workers: 2
Could not inititalize SSL context {:exception=>#<TypeError: can't convert nil into String>
```

This causes Logstash to crash on startup because it's missing many important settings.

**Comment by jordansissel** [comment]
To be honest, my preference would be to just make a TLS input separate from TCP input plugin so that the setting validation would be simpler.

**Comment by harbulot** [comment]
> To be honest, my preference would be to just make a TLS input separate from TCP input plugin so that the setting validation would be simpler.

It could make sense. The downside would be that more or less any changes made to the TCP input would then have to be backported to the TLS input. (It depends on what kind of separation/inheritance you have in mind.)

The same problems happen from a TLS point of view: the TCP input plugin doesn't seem to be the only one in need of SSL/TLS settings. Whatever SSL/TLS settings improvements there are here (e.g. discussed in issue #9), most of them could equally apply to other plugins. (I think the beats plugin also has SSL/TLS settings, for example).

Is there a way to pipe/wrap/nest an input into another? That could be a nice way to generalise the SSL/TLS settings (and also to decouple them). I'm making this up, but there could be something like this:

```
input {
    tls {
        port => 5001
        cert => "..."
        key => "..."
        next => {
            tcp {
                type => "..."
                codec => "..."
            }
        }
    }
}

input {
    tls {
        port => 5002
        cert => "..."
        key => "..."
        next => {
            http {
                 #...
            }
        }
    }
}
```

Of course, it depends on how the wrapped plugin is implemented. Some of them might just be too reliant on sockets.

I'm just mentioning this because the SSL/TLS configuration across plugins seems to be rather disparate. The `http` plugin, for example, uses plain JSSE keystores (but no truststore, no configuration option for client-certificate authentication).

Since it seems logstash runs on Java anyway. Have you considered using a more plain JSSE approach to the SSL/TLS settings in the `tcp` plugin? The OpenSSL way can sometimes feel a bit convoluted, especially when you don't need too advanced customisation. (When looking into issues #9 and #33, I've looked at a bit at the jruby-openssl code to understand what the settings were doing: while some design choices make sense in order to map to the MRI OpenSSL module behaviour, it's overall rather convoluted compared its limited usage within this `tcp` plugin.)
